site_name: GRM Tools Atelier

theme:
  name: material
  palette:
    scheme: slate
  font:
    text: Lato
  logo: assets/app_icon.svg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Atelier:
      - index.md
      - atelier/getting-started.md
      - atelier/modulation.md
      - atelier/multichannel.md
      - atelier/snapshots-and-randomizer.md
      - atelier/midi-and-automation.md
      - atelier/faq.md
  - Modules:
      - modules/index.md
      - Processors:
          - modules/play.md
          - modules/gen.md
          - modules/comb.md
          - modules/band.md
          - modules/pitch.md
          - modules/time.md
          - modules/gain.md
          - modules/viz.md
      - Modulators:
          - modules/agitation.md
          - modules/control.md
          - modules/peak.md
