site_name: GRM Tools Atelier documentation
theme:
  name: material
  palette:
    scheme: slate
  font:
    text: Lato
  logo: assets/app_icon.svg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - index.md
  - Atelier:
      - atelier/getting-started.md
      - atelier/modulation.md
      - atelier/multichannel.md
      - atelier/faq.md
  - Processors:
      - modules/viz.md
      - modules/gain.md
      - modules/gen.md
      - modules/comb.md
      - modules/band.md
      - modules/pitch.md
      - modules/play.md
      - modules/time.md
  - Modulators:
      - modules/agitation.md
      - modules/control.md
      - modules/peak.md
