site_name: GRM Tools Atelier
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: blue
  font:
    text: Lato
  logo: assets/app_icon.svg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Atelier:
      - index.md
      - atelier/getting-started.md
      - atelier/modulation.md
      - atelier/multichannel.md
      - atelier/faq.md
  - Processors:
      - modules/viz.md
      - modules/gain.md
      - modules/gen.md
      - modules/comb.md
      - modules/band.md
      - modules/pitch.md
      - modules/play.md
      - modules/time.md
  - Modulators:
      - modules/agitation.md
      - modules/control.md
      - modules/peak.md
