site_name: GRM Tools Atelier

theme:
  name: material
  palette:
    scheme: slate
  font:
    text: Lato
  logo: assets/app_icon.svg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - attr_list

nav:
  - Atelier:
      - index.md
      - atelier/getting-started.md
      - atelier/modulation.md
      - atelier/multichannel.md
      - atelier/morphing.md
      - atelier/faq.md
  - Modules:
    - modules/index.md
    - Processors:
        - modules/viz.md
        - modules/gain.md
        - modules/gen.md
        - modules/comb.md
        - modules/band.md
        - modules/pitch.md
        - modules/play.md
        - modules/time.md
    - Modulators:
        - modules/agitation.md
        - modules/control.md
        - modules/peak.md
